# -*- coding: utf-8 -*-
"""NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGPatsTrYHLRo8mY5tIYHOVD6wG8lisU
"""

import numpy as np

def sigmoid(x):
  """
  Calculates the logistic sigmoid function using NumPy.

  Args:
    x: A scalar, list, or NumPy array (vector or matrix) of real numbers.

  Returns:
    The sigmoid value(s) as a NumPy array or scalar between 0 and 1.
  """
  return 1 / (1 + np.exp(-x))

def relu(x):
  """
  Calculates the Rectified Linear Unit (ReLU) activation function.

  Args:
    x: A scalar, vector, or matrix input.

  Returns:
    x if x > 0, otherwise 0, applied element-wise.
  """
  return np.maximum(0, x)

def derivate_sigmoid(x):
  """
  Calculates the derivative of the sigmoid function.

  Args:
    x: Input to the sigmoid function.

  Returns:
    The derivative of the sigmoid function at x.
  """
  return sigmoid(x)*(1 - sigmoid(x))

def derivate_relu(x):
  """
  Calculates the derivative of the ReLU function.

  Args:
    x: Input to the ReLU function.

  Returns:
    1 if x > 0, otherwise 0.
  """
  return (x > 0).astype(float)

class NeuralNetwork:
  def __init__(self, layer_dims, sigmoid_func, relu_func, derivate_relu_func):
    self.layer_dims = layer_dims
    self.sigmoid_func = sigmoid_func
    self.relu_func = relu_func
    self.derivate_relu_func = derivate_relu_func
    self.parameters = self._initialize_parameters(layer_dims)

  def _initialize_parameters(self, layer_dims):
    parameters = {}
    for l in range(1, len(layer_dims)):
      parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.01
      parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
    return parameters

  def forward_propagation(self, X):
    activations_result = {}
    linear_outputs = {}

    linear_outputs['Z1'] = self.parameters['W1'] @ X + self.parameters['b1']
    activations_result['A1'] = linear_outputs['Z1']

    for i in range(2, len(self.layer_dims) - 1):
      linear_outputs['Z' + str(i)] = self.parameters['W' + str(i)] @ activations_result['A' + str(i - 1)] + self.parameters['b' + str(i)]
      activations_result['A' + str(i)] = self.relu_func(linear_outputs['Z' + str(i)])

    linear_outputs['Z' + str(len(self.layer_dims) - 1)] = self.parameters['W' + str(len(self.layer_dims) - 1)] @ activations_result['A' + str(len(self.layer_dims) - 2)] + self.parameters['b' + str(len(self.layer_dims) - 1)]
    activations_result['A' + str(len(self.layer_dims) - 1)] = self.sigmoid_func(linear_outputs['Z' + str(len(self.layer_dims) - 1)])

    return activations_result, linear_outputs

  def compute_cost(self, A, Y):
    m = A.shape[1]
    epsilon = 1e-10
    A_clipped = np.clip(A, epsilon, 1 - epsilon)
    cost = - (1/m) * np.sum(Y * np.log(A_clipped) + (1 - Y) * np.log(1 - A_clipped))
    return cost

  def backprop(self, X, Y, activations, linear_outputs):
    m = Y.shape[1]
    dZ = {}
    dW = {}
    db = {}
    dA = {}

    L_out = len(self.layer_dims) - 1

    dZ[str(L_out)] = activations['A' + str(L_out)] - Y
    dW[str(L_out)] = (1/m) * (dZ[str(L_out)] @ activations['A' + str(L_out - 1)].T)
    db[str(L_out)] = (1/m) * np.sum(dZ[str(L_out)], axis=1, keepdims=True)

    for l in range(L_out - 1, 0, -1):
      dA[str(l)] = self.parameters['W' + str(l + 1)].T @ dZ[str(l + 1)]
      dZ[str(l)] = dA[str(l)] * self.derivate_relu_func(linear_outputs['Z' + str(l)])

      if l == 1:
        dW[str(l)] = (1/m) * (dZ[str(l)] @ X.T)
      else:
        dW[str(l)] = (1/m) * (dZ[str(l)] @ activations['A' + str(l - 1)].T)

      db[str(l)] = (1/m) * np.sum(dZ[str(l)], axis=1, keepdims=True)

    return dW, db

  def update_params(self, dW, db, learning_rate):
    num_layers = len(self.parameters) // 2
    for l in range(1, num_layers + 1):
      self.parameters['W' + str(l)] = self.parameters['W' + str(l)] - learning_rate * dW[str(l)]
      self.parameters['b' + str(l)] = self.parameters['b' + str(l)] - learning_rate * db[str(l)]

  def train(self, X_data, Y_data, learning_rate, num_epochs):
    print("Starting training...")
    for epoch in range(1, num_epochs + 1):
      activations, linear_outputs = self.forward_propagation(X_data)
      cost = self.compute_cost(activations['A' + str(len(self.layer_dims) - 1)], Y_data)
      dW, db = self.backprop(X_data, Y_data, activations, linear_outputs)
      self.update_params(dW, db, learning_rate)
      print(f"Epoch {epoch}/{num_epochs}, Cost: {cost:.6f}")
    print("Training finished.")

# Initialize network architecture and hyperparameters
layers = [2, 4, 3, 1]  # 2 input features, 4 neurons in first hidden layer, 3 in second, 1 output neuron
learning_rate = 0.2 # Increased learning rate
num_epochs = 2000 # Increased epochs to observe convergence better

# Generate a simple, linearly separable dataset
num_samples = 200
np.random.seed(42) # for reproducibility
X_data = np.random.randn(layers[0], num_samples) # 2 features, num_samples examples
# Create a simple linear boundary: Y is 1 if X[0] + X[1] > 0, else 0
Y_data = (X_data[0, :] + X_data[1, :] > 0).astype(float).reshape(1, -1)

# Create a NeuralNetwork instance
# Ensure the NeuralNetwork class (defined in cell a4ab8017) is executed before this cell.
nn_model = NeuralNetwork(layers, sigmoid, relu, derivate_relu)

# Train the model
nn_model.train(X_data, Y_data, learning_rate, num_epochs)

# You can inspect the final parameters or make predictions if needed
# print("Final parameters:", nn_model.parameters)

from tensorflow.keras.datasets import mnist

# Load the MNIST dataset
(X_train_full, y_train_full), (X_test_full, y_test_full) = mnist.load_data()

# Filter for digits 0 and 1 for binary classification
# Select training data
idx_train_0_1 = (y_train_full == 0) | (y_train_full == 1)
X_train_0_1 = X_train_full[idx_train_0_1]
y_train_0_1 = y_train_full[idx_train_0_1]

# Select test data (optional, just for completeness)
idx_test_0_1 = (y_test_full == 0) | (y_test_full == 1)
X_test_0_1 = X_test_full[idx_test_0_1]
y_test_0_1 = y_test_full[idx_test_0_1]

# Flatten images (28x28 = 784 pixels) and normalize to [0, 1]
X_train_flat = X_train_0_1.reshape(X_train_0_1.shape[0], -1).T / 255.0
# For simplicity, we'll use a subset of the training data as X_data
# The network expects shape (features, samples)
X_data_mnist = X_train_flat[:, :num_samples] # Use 'num_samples' from the next cell

# Reshape labels to (1, num_samples)
Y_data_mnist = y_train_0_1[:num_samples].reshape(1, -1)

print(f"Shape of X_data_mnist: {X_data_mnist.shape}")
print(f"Shape of Y_data_mnist: {Y_data_mnist.shape}")
print(f"First 5 labels: {Y_data_mnist[0, :5]}")

# Initialize network architecture and hyperparameters
layers = [784, 128, 64, 1]  # 784 input features (28x28 MNIST), hidden layers, 1 output neuron
learning_rate = 0.05 # Adjusted learning rate for MNIST
num_epochs = 500 # Increased epochs for better convergence on MNIST

# num_samples will be defined in the previous cell now
# Generate a simple, linearly separable dataset (will be overwritten by MNIST)
# num_samples = 200 # This line is moved to the MNIST preprocessing cell
# np.random.seed(42) # for reproducibility
# X_data = np.random.randn(layers[0], num_samples) # 2 features, num_samples examples
# Create a simple linear boundary: Y is 1 if X[0] + X[1] > 0, else 0
# Y_data = (X_data[0, :] + X_data[1, :] > 0).astype(float).reshape(1, -1)

# Make sure num_samples is defined before X_data_mnist is created
num_samples = 2000 # Example num_samples for MNIST subset. This will be used in the previous cell.

# Use MNIST data
X_data = X_data_mnist
Y_data = Y_data_mnist

# Create a NeuralNetwork instance
# Ensure the NeuralNetwork class (defined in cell a4ab8017) is executed before this cell.
nn_model = NeuralNetwork(layers, sigmoid, relu, derivate_relu)

# Train the model
nn_model.train(X_data, Y_data, learning_rate, num_epochs)

# You can inspect the final parameters or make predictions if needed
# print("Final parameters:", nn_model.parameters)

# Prepare the test data (already loaded in cell e65503f6)
# Flatten images (28x28 = 784 pixels) and normalize to [0, 1]
X_test_flat = X_test_0_1.reshape(X_test_0_1.shape[0], -1).T / 255.0

# Reshape labels to (1, num_samples)
Y_test_reshaped = y_test_0_1.reshape(1, -1)

print(f"Shape of X_test_flat: {X_test_flat.shape}")
print(f"Shape of Y_test_reshaped: {Y_test_reshaped.shape}")

# Make predictions on the test data
activations_test, _ = nn_model.forward_propagation(X_test_flat)

# The final layer's activation (A'L') contains the probabilities
Y_predictions_probs = activations_test['A' + str(len(nn_model.layer_dims) - 1)]

# Convert probabilities to binary predictions (0 or 1) using a threshold (e.g., 0.5)
Y_predictions = (Y_predictions_probs > 0.5).astype(float)

# Calculate accuracy
accuracy = np.mean(Y_predictions == Y_test_reshaped) * 100

print(f"\nPrediction Accuracy on Test Data: {accuracy:.2f}%")